### ISSUE TITLE
Option to have smooth lines instead of hard ones.

### ISSUE THREAD

**Issue by vanniktech** [robinhood/spark#30]
I don't know whether you guys want to support this or not. I was just playing around with it and wanted to mentioned it. This can be achieved by the code below:

```diff
diff --git a/spark/src/main/java/com/robinhood/spark/SparkView.java b/spark/src/main/java/com/robinhood/spark/SparkView.java
index 505b14f..5d99c21 100644
--- a/spark/src/main/java/com/robinhood/spark/SparkView.java
+++ b/spark/src/main/java/com/robinhood/spark/SparkView.java
@@ -184,7 +184,12 @@ public class SparkView extends View implements ScrubGestureDetector.ScrubListene
             if (i == 0) {
                 sparkPath.moveTo(x, y);
             } else {
-                sparkPath.lineTo(x, y);
+                final float prevx = scaleHelper.getX(adapter.getX(i - 1));
+                final float prevy = scaleHelper.getY(adapter.getY(i - 1));
+
+                final float smoothness = 0.5f;
+                final float dX = x - prevx;
+                sparkPath.cubicTo(prevx + dX * smoothness, prevy, x - dX * smoothness, y, x, y);
             }
 
             if (scrubEnabled) {
```

This is how it would look like:

<img width="550" alt="screen shot 2017-03-14 at 11 41 35" src="https://cloud.githubusercontent.com/assets/5759366/23896877/34520906-08ab-11e7-8785-7a58d91233de.png">

The smoothness can be changed by adjusting `smoothness`.

**Comment by danh32** [comment]
I did a quick overlay test:

![screen shot 2017-03-14 at 9 33 35 am](https://cloud.githubusercontent.com/assets/447085/23911479/322e046a-089a-11e7-872f-07819d100e52.png)

In the screenshot, the green is smoothed and the underlying red is normal. It looks like the green is creating little curves where there normally is none. I don't think that's a good behavior for Spark since the only indication we get of where the actual points are are where there are natural curves on the sparkline. This seems to create new ones where there aren't any underlying points.

Spark already has a `spark_cornerRadius` attribute that curves the between the line segments. Is this the effect you were going for?

**Comment by vanniktech** [comment]
To be honest I was just playing around with it and wanted to mention it in case anyone else needs this special behavior. My use case is a temperature graph and there those little curves actually make sense since the difference between each data point is minimal (~0.5 at most) and that way the graph looks nicer.

I have tried out `spark_cornerRadius` and that one also looks nice.

About the curves, yes some of them are due to the 'smoothness' behavior change although some of them are actual data points you just don't see them on the graph since they are more or less the same e.g. the ones here:

<img width="47" alt="screen shot 2017-03-14 at 17 54 38" src="https://cloud.githubusercontent.com/assets/5759366/23912221/50a01646-08df-11e7-8b77-8132cc144b67.png">

**Comment by danh32** [comment]
Ah I see! Due to the additional API surface area we'd rather not pull this into Spark proper. But thanks for sharing!
